# ------------------- Deployment ------------------- #
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1
  namespace: default
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 2
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
      - name: test1
        image: orangebal/nginx-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---

# ------------------- Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: default
  labels:
    app: test1
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: test1
